name: Build Windows Only

on:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Windows exe
        run: npm run dist:win
